<?php
/* Here are the functions utilized in this page */
include "../../function/print_header.php";
include "../../function/print_foot.php";
include "../../function/print_block.php";
?>

<html>
<head>
	<link  rel = "stylesheet" type = "text/css" href = "../../style_index.css">
	<link  rel = "stylesheet" type = "text/css" href = "../../style_block.css">
</head>

<body>
	<!-- print header | lv index is 2 -->
	<?php echo pageHead(1,2)?>
	
	<!-- Here is the main body -->
	<!-- print the menu -->
	<?php 
	
		$currrent_block_index = 0; 
		$lv_index = 1;
		echo print_research_navi($currrent_block_index, $lv_index);
		
		$currrent_section_index = 0;
		echo print_in_progress_navi($currrent_section_index);		
	?>
	<!-- print the main block -->
			<div id = "displayPanel">
				<div id = "unit">
				<h2>Define the Problem</h2>
									
					<p>My focus is on the special case that <span id="codeMaroon">the propensity score is generated by a mixture model</span>.<br>
					Not all variables can be modelled as mean difference so mixture model is closer to reality, but considerably harder to model and estimate.<br>
					
					
					<p>How does HIR estimator do when the true propensity score comes from a mixture model?<br>
					Spoiler alert, not so well.				
				</div>
				
				<div id = "unit">	
					<h2>Nonparametric Bayes, aka Hierarchical Dirichlet Process</h2>
					
					<p> The orthodoxical nonparametric Bayes response is hierarchical Dirichlet Process. 
					<p> Advantage: It can potentially handle high dimensional data. Its variation can handle various parametric function forms of the likelihood functions, thus very flexible.							
					<p> Disadvantage: It does not have any theoretical consistency property. It depends crucially on how to specify the Dirichlet process.<br>
						In addition, instead of one propensity score, one got a distribution of propensity score. It is not clear how various matching technique should adapt.							
					
					<div id="download"> 
						<a href="../files/hdp_bayes_10062012.pdf" target=_blank>Tech Paper</a>
					</div>
				</div>
				
				<div id = "unit">	
					<h2>Adaboost</h2>
					
					<p> daboost is a Machine Learning trick invented in 1990s. The idea is to combine the preditive power of a series of "dumb" predictors. 
					<p> Advantage: The empirical predictive performance of the adaboost is said to be quite good. It fits the tail really well!							
					<p> Disadvantage: No theorectial guarantee that the propensity is weakly learnable by the base learner one picks. 
					<br>Hard to use on high deminsions, which is prevasive in kitchen-sink style propensity estimator.
					<div id="download"> 
						<a href="../files/adaboost_02142013.pdf" target=_blank>Presentation</a>
					</div>
				</div>
				
				<div id= "unit">
					<h2>Spline logit</h2>
					During Professor Black's seminar, he suggests that a spline within the logit function would fit the data well.
					<p> Yet to be tried.
				</div>
				
				<div id = "unit">
					<h2> RKHS version of the polynomial logit</h2>
						<p>
							The problem with the polynomial logit is numerical instability. Another practical concern is that very few would indeed take as 							many degree of polynomials and their interaction as needed.<br>
							A remedy for that is to work with the Reproducing Kernel Hilbert Space, rather than the original image space.<br>
							More importantly, there are more ways to do approximation than taylor expansion. Gaussian Kernel is equivalent of Fourier 							transform.
						
						<p>
							The question is, can we get RKHS representation inside a logit? It is possible that the optimal solution cannot be expressed as 							inner product of kernels.
						
						<p>
							This approach is yet to be tried.
											
				</div>
			
				
				
			</div>	
	<!-- print footer -->
	<?php echo page_foot()?>
</body>


</html>